# Generated by Django 3.1.7 on 2021-03-26 22:27

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Marca')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FermentativeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Perfil Fermentativo')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Processo Fermentativo',
                'verbose_name_plural': 'Processos Fermentativos',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Yeast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('number', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Adicionado ao banco')),
                ('last_reinnoculation', models.DateField(verbose_name='Última repicagem')),
                ('next_reinnoculation_limit_date', models.DateField(verbose_name='Próxima repicagem')),
                ('reinnoculation_count', models.PositiveIntegerField(verbose_name='Quantidade de repiques')),
                ('attenuation', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Atenuação')),
                ('flocculation', models.CharField(choices=[('Alta', 'Alta'), ('Média', 'Média'), ('Baixa', 'Baixa'), ('N/D', 'N/D')], default='N/D', max_length=5, verbose_name='Floculação')),
                ('datasheet', models.FileField(blank=True, null=True, upload_to='datasheets', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='PDF')),
                ('polyphenol', models.CharField(choices=[('+', '+'), ('-', '-')], default='+', max_length=1, verbose_name='PoF')),
                ('amyloglucosidase', models.CharField(choices=[('+', '+'), ('-', '-')], default='+', max_length=1, verbose_name='AMG')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leveduras.brand', verbose_name='Marca')),
                ('fermentative_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leveduras.fermentativeprofile', verbose_name='Perfil Fermentativo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Levedura',
                'verbose_name_plural': 'Leveduras',
                'ordering': ('name',),
            },
        ),
    ]
