# Generated by Django 3.1.7 on 2021-03-29 20:17

from django.conf import settings
from django.db import migrations, models
import leveduras.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leveduras', '0003_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='content_id',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='content_type',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=models.SET(leveduras.models.get_sentinel_user), to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
